<a href="https://colab.research.google.com/github/GANDLASUMANTH/ML/blob/main/Social_Network_Ads.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Verzeo_python/Social_Network_Ads.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
dataset=pd.get_dummies(dataset)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0              0            1
1    15810944   35            20000          0              0            1
2    15668575   26            43000          0              1            0
3    15603246   27            57000          0              1            0
4    15804002   19            76000          0              0            1
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1              1            0
396  15706071   51            23000          1              0            1
397  15654296   50            20000          1              1            0
398  15755018   36            33000          0              0            1
399  15594041   49            36000          1              1            0

[400 rows x 6 columns]

In [ ]:
X=dataset.drop(['Purchased'],axis=1)
y=dataset['Purchased']

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)

      User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
336  15664907   58           144000              0            1
64   15605000   59            83000              1            0
55   15649136   24            55000              1            0
106  15706185   26            35000              1            0
300  15736397   58            38000              1            0
..        ...  ...              ...            ...          ...
323  15619465   48            30000              1            0
192  15779581   29            43000              0            1
117  15591433   36            52000              0            1
47   15776348   27            54000              1            0
172  15794661   26           118000              1            0

[320 rows x 5 columns]


In [ ]:
print(y_train)

336    1
64     0
55     0
106    0
300    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 320, dtype: int64


In [ ]:
print(X_test)

      User ID  Age  EstimatedSalary  Gender_Female  Gender_Male
132  15725660   30            87000              0            1
309  15652400   38            50000              1            0
341  15776844   35            75000              0            1
196  15738448   30            79000              1            0
246  15638003   35            50000              1            0
..        ...  ...              ...            ...          ...
14   15628972   18            82000              0            1
363  15768293   42            79000              1            0
304  15598070   40            60000              1            0
361  15778830   53            34000              1            0
329  15639576   47           107000              1            0

[80 rows x 5 columns]


In [ ]:
print(y_test)

132    0
309    0
341    0
196    0
246    0
      ..
14     0
363    0
304    0
361    1
329    1
Name: Purchased, Length: 80, dtype: int64


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.37311852  1.92295008  2.14601566 -1.02532046  1.02532046]
 [-1.22319878  2.02016082  0.3787193   0.97530483 -0.97530483]
 [-0.596909   -1.3822153  -0.4324987   0.97530483 -0.97530483]
 ...
 [-1.4157145  -0.21568634 -0.51941492 -1.02532046  1.02532046]
 [ 1.20822913 -1.09058306 -0.46147078  0.97530483 -0.97530483]
 [ 1.46809058 -1.18779381  1.3927418   0.97530483 -0.97530483]]


In [ ]:
print(X_test)

[[ 4.88966473e-01 -7.98950822e-01  4.94607583e-01 -1.02532046e+00
   1.02532046e+00]
 [-5.50592839e-01 -2.12648508e-02 -5.77359062e-01  9.75304830e-01
  -9.75304830e-01]
 [ 1.21526737e+00 -3.12897090e-01  1.46942725e-01 -1.02532046e+00
   1.02532046e+00]
 [ 6.70428177e-01 -7.98950822e-01  2.62831011e-01  9.75304830e-01
  -9.75304830e-01]
 [-7.54886252e-01 -3.12897090e-01 -5.77359062e-01  9.75304830e-01
  -9.75304830e-01]
 [ 1.74256773e+00 -1.09058306e+00 -1.44652121e+00 -1.02532046e+00
   1.02532046e+00]
 [-1.15026219e+00 -7.01740076e-01 -1.59138156e+00  9.75304830e-01
  -9.75304830e-01]
 [-1.50619343e-01 -2.15686344e-01  2.14601566e+00 -1.02532046e+00
   1.02532046e+00]
 [-3.55608066e-01 -1.96547978e+00 -5.58617754e-02  9.75304830e-01
  -9.75304830e-01]
 [-9.75185983e-01  8.53631867e-01 -7.80163563e-01 -1.02532046e+00
   1.02532046e+00]
 [-2.52081338e-02 -7.98950822e-01 -6.06331134e-01 -1.02532046e+00
   1.02532046e+00]
 [ 1.54471657e+00 -9.93372315e-01 -4.32498705e-01  9.75304830e-01

## Training the SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[15624510,	19,	19000,	0,	1	]])))

[0]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56  2]
 [ 5 17]]


0.9125